/* BIS SmartGuide V7 — complete feature console. Does not replace the existing app router. */
(()=>{
'use strict';
const API='https://sih26107-bis-smartguide-api.onrender.com';
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||d.message||'Request failed');return d}
const features=[
['User modes','Consumer, Manufacturer, MSME, Startup, Importer, Laboratory and Procurement workflows','Workspace'],
['ISI mark image verification','Image intake, mark/CM-L screening and official verification handoff','Vision'],
['Full CM/L verification','Format check plus manufacturer/product/scope/status verification handoff','Official source'],
['Counterfeit reporting','Suspected fake mark, logo, non-certified product and evidence case drafting','Consumer'],
['3D CAD / STL scanner','STL upload, geometry dimensions, supplied limits and deviation screening','Engineering'],
['Intelligent laboratory finder','Required test, standard, capability and lab-scope matching','Labs'],
['Geographic lab routing','Rank candidate labs by user-entered location and distance','Maps'],
['Map / navigation','Open directions for a selected laboratory','Navigation'],
['Test → laboratory matching','Product → IS → required test → capable laboratory workflow','Labs'],
['Gazette / amendment watcher','Tracked standards/QCO changes with source-required update queue','Monitoring'],
['Proactive amendment alerts','Alert cards for standards used by saved products/assessments','Alerts'],
['Amendment impact analysis','Compare notice text with affected standards/assessments','Compliance'],
['Procurement mode','Procurement specification → IS → QCO → certification → testing','Procurement'],
['HS-code recommendations','Combine HS code with product description and technical context','Trade'],
['Raw material intelligence','Raw material/component → finished product → standard pathway','Manufacturing'],
['Label / packaging compliance','Extract product, maker, model, IS, CM/L and rating fields','Labelling'],
['Product photo identification','Photo intake → product hypothesis → standard search workflow','Vision'],
['Voice-first workflow','Voice query, answer, navigation and follow-up hooks','Accessibility'],
['Indian language support','English, Hindi, Telugu, Kannada, Tamil, Malayalam and more','Languages'],
['Language-aware voice + text','Keep selected language through query, answer and speech pipeline','Accessibility'],
['PWA / mobile workspace','Installable web app shell and responsive feature console','Mobile'],
['Offline / low-connectivity','Cached shell, saved products and local draft workflows','Offline'],
['Saved products','Persist products, standards and assessments locally until account sync exists','Workspace'],
['Organization workspace','Company products, documents, labs, passports and corrective actions','Enterprise'],
['Multi-user roles','Admin, compliance, engineer, reviewer, auditor and viewer role model','Enterprise'],
['Enterprise audit trail','Actor, time, action, old/new value and document/assessment version fields','Audit'],
['Document version control','Save versions and compare extracted values/change notes','Documents'],
['Test-report intelligence','Extract measurements and compare only against supplied/verified limits','Testing'],
['Compliance trend analytics','Risk, failures, corrective-action closure and assessment history trends','Analytics'],
['Requirement dependency graph','Product → standard → clause → requirement → test → lab → certificate/QCO','Knowledge graph'],
['Clause-level evidence viewer','Standard → clause → page → evidence chain','Evidence'],
['Hybrid search','Keyword/BM25 + semantic retrieval + metadata + reranking hook','Retrieval'],
['Confidence + citation quality','Confidence, source authority and explainability panel','Explainability'],
['Unsupported-answer refusal','Evidence guard that refuses unsupported claims instead of guessing','Trust'],
['Human review workflow','Review required → reviewer → approve/reject/modify with audit fields','Governance']
];
function callOriginalPage(id,btn,title){const p=window.page;if(typeof p==='function'&&p!==sg7Router)p(id,btn,title)}
function nav(){const n=document.querySelector('.nav');if(!n)return;let b=$('sg7Nav');if(!b){b=document.createElement('button');b.id='sg7Nav';b.innerHTML='<span>✦</span><span>Advanced Intelligence</span>';n.appendChild(b)}b.onclick=()=>{callOriginalPage('sg7',b,'Advanced Intelligence');show();loadStatus()};return b}
function show(){let s=$('sg7');if(!s){const m=document.querySelector('.content');if(!m)return;s=document.createElement('section');s.id='sg7';s.className='page';m.appendChild(s)}document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));s.classList.add('active');render(s)}
function render(s){if(s.dataset.rendered)return;s.dataset.rendered='1';s.innerHTML=`<div class="sg7-shell"><div class="sg7-hero"><div class="eyebrow">BIS SMARTGUIDE · V7</div><h1>Advanced Intelligence</h1><p>35 compliance, engineering, evidence and enterprise capabilities in one workspace.</p><div class="sg7-toolbar"><select id="sg7Role"><option>Consumer</option><option>Manufacturer</option><option>MSME</option><option>Startup</option><option>Importer</option><option>Laboratory</option><option>Procurement</option></select><input id="sg7Save" placeholder="Save a product name"><button class="btn primary" onclick="sg7SaveProduct()">Save product</button><button class="btn ghost" onclick="sg7Open('status')">System status</button></div></div><div class="sg7-grid">${features.map((f,i)=>`<div class="sg7-card"><span class="sg7-pill ${['Official source','Maps','Vision'].includes(f[2])?'source':'local'}">${esc(f[2])}</span><h3>${i+1}. ${esc(f[0])}</h3><p>${esc(f[1])}</p><button class="btn primary" onclick="sg7Open(${i})">Open workflow</button></div>`).join('')}</div><div id="sg7Output" class="sg7-output"></div></div><div id="sg7Offline" class="sg7-offline">Offline-ready shell</div>`}
function panel(title,body){const o=$('sg7Output');o.innerHTML=`<div class="sg7-panel"><button class="btn ghost sg7-close" onclick="$('sg7Output').innerHTML=''">Close</button><h2>${esc(title)}</h2>${body}</div>`;o.scrollIntoView({behavior:'smooth',block:'start'})}
function result(x){return `<div id="sg7Result" class="sg7-result">${esc(JSON.stringify(x,null,2))}</div>`}
window.sg7Open=i=>{
if(i==='status'){panel('Feature status','<p>Loading current backend status…</p><div id="sg7Result"></div>');loadStatus();return}
const f=features[i];if(!f)return;
const forms={
0:`<div class="sg7-form"><select id="rMode"><option>Consumer</option><option>Manufacturer</option><option>MSME</option><option>Startup</option><option>Importer</option><option>Laboratory</option><option>Procurement</option></select><input id="rProduct" placeholder="Product"><textarea id="rSpec" class="full" placeholder="Product/specification or user need"></textarea><button class="btn primary" onclick="sg7RoleFlow()">Start workflow</button></div><div id="sg7Result"></div>`,
1:`<div class="sg7-form"><input id="photo" type="file" accept="image/*" class="full"><button class="btn primary" onclick="sg7Photo()">Inspect image</button></div><div id="sg7Result"></div><div class="sg7-note">Image intake is a screening workflow. Licence/product identity must be confirmed through official BIS sources.</div>`,
2:`<div class="sg7-form"><input id="cmlic" placeholder="CM/L number"><button class="btn primary" onclick="sg7CM()">Check CM/L</button></div><div id="sg7Result"></div>`,
3:`<div class="sg7-form"><input id="issueProduct" placeholder="Product"><textarea id="issueText" class="full" placeholder="Describe suspected counterfeit/non-compliance"></textarea><button class="btn primary" onclick="sg7Issue()">Create report draft</button></div><div id="sg7Result"></div>`,
4:`<div class="sg7-form"><input id="stl" type="file" accept=".stl" class="full"><input id="mx" placeholder="Max X (optional)"><input id="my" placeholder="Max Y (optional)"><input id="mz" placeholder="Max Z (optional)"><button class="btn primary" onclick="sg7STL()">Scan STL</button></div><div id="sg7Result"></div>`,
5:`<div class="sg7-form"><input id="lp" placeholder="Product"><input id="ls" placeholder="IS number"><input id="lt" class="full" placeholder="Required test/parameter"><button class="btn primary" onclick="sg7Lab()">Match laboratories</button></div><div id="sg7Result"></div>`,
6:`<div class="sg7-form"><input id="glab" placeholder="Laboratory name"><input id="gloc" placeholder="Destination/location"><button class="btn primary" onclick="sg7Directions()">Open directions</button></div><div id="sg7Result"></div>`,
7:`<div class="sg7-form"><input id="navLab" placeholder="Laboratory name"><input id="navFrom" placeholder="From location"><button class="btn primary" onclick="sg7Directions()">Navigate</button></div><div id="sg7Result"></div>`,
8:`<div class="sg7-form"><input id="tp" placeholder="Product"><input id="ts" placeholder="IS number"><textarea id="tt" class="full" placeholder="Required tests"></textarea><button class="btn primary" onclick="sg7Lab()">Find test-capable labs</button></div><div id="sg7Result"></div>`,
9:`<div class="sg7-form"><input id="watchStd" placeholder="Standard / QCO"><textarea id="watchText" class="full" placeholder="Paste verified Gazette/QCO/amendment text to track"></textarea><button class="btn primary" onclick="sg7SaveWatch()">Save monitored update</button></div><div id="sg7Result"></div>`,
10:`<div class="sg7-form"><input id="alertStd" placeholder="Standard"><input id="alertProduct" placeholder="Saved product"><button class="btn primary" onclick="sg7Local('alert', {standard:$('alertStd').value,product:$('alertProduct').value})">Create alert rule</button></div><div id="sg7Result"></div>`,
11:`<div class="sg7-form"><input id="amStd" placeholder="Standard"><input id="amProduct" placeholder="Product"><textarea id="amText" class="full" placeholder="Paste amendment/QCO notice"></textarea><button class="btn primary" onclick="sg7Amendment()">Analyze impact</button></div><div id="sg7Result"></div>`,
12:`<div class="sg7-form"><input id="pp" placeholder="Procurement product"><input id="phs" placeholder="HS code"><input id="praw" class="full" placeholder="Raw material/component"><button class="btn primary" onclick="sg7Procurement()">Screen procurement</button></div><div id="sg7Result"></div>`,
13:`<div class="sg7-form"><input id="hsProduct" placeholder="Product"><input id="hs" placeholder="HS code"><button class="btn primary" onclick="sg7Procurement()">Recommend standards</button></div><div id="sg7Result"></div>`,
14:`<div class="sg7-form"><input id="rawProduct" placeholder="Finished product"><input id="raw" class="full" placeholder="Raw material/component"><button class="btn primary" onclick="sg7Procurement()">Map pathway</button></div><div id="sg7Result"></div>`,
15:`<div class="sg7-form"><textarea id="label" class="full" placeholder="Paste label/packaging text"></textarea><button class="btn primary" onclick="sg7Label()">Check label</button></div><div id="sg7Result"></div>`,
16:`<div class="sg7-form"><input id="prodPhoto" type="file" accept="image/*" class="full"><textarea id="photoDesc" class="full" placeholder="Optional visual/product description"></textarea><button class="btn primary" onclick="sg7PhotoProduct()">Start identification</button></div><div id="sg7Result"></div>`,
17:`<div class="sg7-form"><select id="voiceLang"><option>English</option><option>Hindi</option><option>Telugu</option><option>Kannada</option><option>Tamil</option></select><input id="voiceText" placeholder="Voice/text query"><button class="btn primary" onclick="sg7Speak()">Speak / listen</button></div><div id="sg7Result"></div>`,
18:`<div class="sg7-form"><select id="lang"><option>English</option><option>Hindi</option><option>Telugu</option><option>Kannada</option><option>Tamil</option><option>Malayalam</option><option>Marathi</option><option>Bengali</option><option>Gujarati</option><option>Punjabi</option><option>Odia</option><option>Assamese</option><option>Urdu</option></select><button class="btn primary" onclick="sg7Local('language',$('lang').value)">Set language</button></div><div id="sg7Result"></div>`,
19:`<div class="sg7-form"><select id="lang2"><option>English</option><option>Hindi</option><option>Telugu</option><option>Kannada</option><option>Tamil</option><option>Malayalam</option></select><textarea id="langQuery" class="full" placeholder="Query in selected language"></textarea><button class="btn primary" onclick="sg7Speak()">Run language pipeline</button></div><div id="sg7Result"></div>`,
20:`<p>Your existing responsive HTML app is now an installable PWA shell. Use your browser's install option when supported.</p><button class="btn primary" onclick="sg7RegisterPWA()">Check PWA</button><div id="sg7Result"></div>`,
21:`<p>Saved products, drafts and selected language are stored locally for low-connectivity use. Server-backed verification still requires connectivity.</p><button class="btn primary" onclick="sg7Local('offline','enabled')">Enable offline drafts</button><div id="sg7Result"></div>`,
22:`<div class="sg7-form"><input id="saveProd" placeholder="Product name"><input id="saveStd" placeholder="Standard"><button class="btn primary" onclick="sg7SaveProduct2()">Save</button></div><div id="sg7Result"></div>`,
23:`<div class="sg7-form"><input id="org" placeholder="Organization"><input id="orgProduct" placeholder="Product portfolio"><textarea id="orgDocs" class="full" placeholder="Documents / labs / passport notes"></textarea><button class="btn primary" onclick="sg7Local('org',{name:$('org').value,product:$('orgProduct').value,notes:$('orgDocs').value})">Create workspace draft</button></div><div id="sg7Result"></div>`,
24:`<div class="sg7-form"><select id="role"><option>Admin</option><option>Compliance Officer</option><option>Engineer</option><option>Reviewer</option><option>Auditor</option><option>Viewer</option></select><input id="member" placeholder="Member name/identifier"><button class="btn primary" onclick="sg7Local('member',{role:$('role').value,member:$('member').value})">Assign role</button></div><div id="sg7Result"></div>`,
25:`<div class="sg7-form"><input id="actor" placeholder="Actor"><input id="action" placeholder="Action"><input id="oldv" placeholder="Previous value"><input id="newv" placeholder="New value"><button class="btn primary" onclick="sg7Local('audit',{actor:$('actor').value,action:$('action').value,old:$('oldv').value,new:$('newv').value,at:new Date().toISOString()})">Record audit event</button></div><div id="sg7Result"></div>`,
26:`<div class="sg7-form"><input id="docName" placeholder="Document name"><input id="docVersion" placeholder="Version"><textarea id="docNotes" class="full" placeholder="Changes from previous version"></textarea><button class="btn primary" onclick="sg7Local('document',{name:$('docName').value,version:$('docVersion').value,notes:$('docNotes').value})">Save version</button></div><div id="sg7Result"></div>`,
27:`<div class="sg7-form"><input id="trStd" placeholder="IS number"><textarea id="trText" class="full" placeholder="Paste test report measurements"></textarea><button class="btn primary" onclick="sg7Test()">Analyze report</button></div><div id="sg7Result"></div>`,
28:`<button class="btn primary" onclick="sg7Analytics()">Build local assessment analytics</button><div id="sg7Result"></div>`,
29:`<button class="btn primary" onclick="sg7Graph()">Open compliance dependency graph</button><div id="sg7Result"></div>`,
30:`<div class="sg7-form"><input id="evStd" placeholder="IS / standard"><input id="evClause" placeholder="Clause"><input id="evPage" placeholder="Page"><textarea id="evEvidence" class="full" placeholder="Evidence reference / test report page"></textarea><button class="btn primary" onclick="sg7Local('evidence',{standard:$('evStd').value,clause:$('evClause').value,page:$('evPage').value,evidence:$('evEvidence').value})">Create evidence chain</button></div><div id="sg7Result"></div>`,
31:`<div class="sg7-form"><input id="hybridQ" class="full" placeholder="Exact IS number, clause or product query"><button class="btn primary" onclick="sg7Hybrid()">Hybrid search</button></div><div id="sg7Result"></div>`,
32:`<div class="sg7-form"><input id="conf" placeholder="Confidence %"><input id="cite" placeholder="Citation quality"><textarea id="why" class="full" placeholder="Why this answer is supported"></textarea><button class="btn primary" onclick="sg7Local('explain',{confidence:$('conf').value,citation_quality:$('cite').value,why:$('why').value})">Save explanation</button></div><div id="sg7Result"></div>`,
33:`<div class="sg7-form"><textarea id="guard" class="full" placeholder="Paste an answer and its evidence/source"></textarea><button class="btn primary" onclick="sg7Guard()">Run evidence guard</button></div><div id="sg7Result"></div>`,
34:`<div class="sg7-form"><input id="reviewCase" placeholder="Assessment/case ID"><select id="reviewDecision"><option>REVIEW_REQUIRED</option><option>APPROVE</option><option>REJECT</option><option>MODIFY</option></select><textarea id="reviewNote" class="full" placeholder="Reviewer note"></textarea><button class="btn primary" onclick="sg7Review()">Record review</button></div><div id="sg7Result"></div>`};
panel(f[0],forms[i]||'<p>Workflow ready.</p>')
};
window.sg7RoleFlow=()=>sg7Local('mode',{mode:$('rMode').value,product:$('rProduct').value,spec:$('rSpec').value,next:'Personalized BIS workflow'});
window.sg7Local=(key,value)=>{localStorage.setItem('sg7_'+key,JSON.stringify(value));$('sg7Result').textContent=JSON.stringify({saved:true,key,value},null,2)};
window.sg7SaveProduct=()=>{const v=$('sg7Save').value.trim();if(v)localStorage.setItem('sg7_products',JSON.stringify([...JSON.parse(localStorage.getItem('sg7_products')||'[]'),{name:v,at:new Date().toISOString()}]));$('sg7Save').value='';alert('Product saved locally')};
window.sg7SaveProduct2=()=>sg7Local('product',{name:$('saveProd').value,standard:$('saveStd').value,at:new Date().toISOString()});
window.sg7CM=async()=>{try{$('sg7Result').textContent=JSON.stringify(await api('/v5/verify-mark',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({licence:$('cmlic').value,text:'CM/L '+$('cmlic').value})}),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7Issue=async()=>{try{$('sg7Result').textContent=JSON.stringify(await api('/v5/issue-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:$('issueProduct').value,issue:$('issueText').value})}),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7STL=async()=>{try{const f=$('stl').files[0];if(!f)return $('sg7Result').textContent='Select an STL file';const fd=new FormData();fd.append('file',f);if($('mx').value)fd.append('max_x',$('mx').value);if($('my').value)fd.append('max_y',$('my').value);if($('mz').value)fd.append('max_z',$('mz').value);$('sg7Result').textContent=JSON.stringify(await api('/v5/stl-scan',{method:'POST',body:fd}),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7Lab=async()=>{try{const q=new URLSearchParams({product:($('lp')||$('tp'))?.value||'',standard:($('ls')||$('ts'))?.value||'',test:($('lt')||$('tt'))?.value||''});$('sg7Result').textContent=JSON.stringify(await api('/v5/lab-match?'+q),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7Directions=()=>{const lab=($('glab')||$('navLab'))?.value||'BIS laboratory';const from=($('gloc')||$('navFrom'))?.value||'';const url='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(lab)+(from?'&origin='+encodeURIComponent(from):'');$('sg7Result').innerHTML='<a class="sg7-map" target="_blank" rel="noopener" href="'+url+'">Open map directions</a>'};
window.sg7SaveWatch=()=>sg7Local('watch',{standard:$('watchStd').value,text:$('watchText').value,checked_at:new Date().toISOString(),status:'SOURCE_UPDATE_REQUIRED'});
window.sg7Amendment=async()=>{try{$('sg7Result').textContent=JSON.stringify(await api('/v5/amendment-impact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({standard:$('amStd').value,product:$('amProduct').value,amendment:$('amText').value})}),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7Procurement=async()=>{try{$('sg7Result').textContent=JSON.stringify(await api('/v5/procurement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:($('pp')||$('hsProduct')||$('rawProduct'))?.value||'',hs_code:$('phs')?.value||$('hs')?.value||'',raw_material:$('praw')?.value||$('raw')?.value||''})}),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7Label=async()=>{try{$('sg7Result').textContent=JSON.stringify(await api('/v5/label-check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('label').value})}),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7Photo=()=>{const f=$('photo').files[0];$('sg7Result').textContent=JSON.stringify({file:f?.name||null,status:'IMAGE_INTAKE_READY',next:['Detect ISI mark','Read CM/L','Match manufacturer/product','Confirm through official BIS source']},null,2)};
window.sg7PhotoProduct=()=>{const f=$('prodPhoto').files[0];$('sg7Result').textContent=JSON.stringify({file:f?.name||null,description:$('photoDesc').value,status:'PRODUCT_IDENTIFICATION_SCREEN',next:'Use description and retrieved evidence to identify candidate standards; do not treat image inference as certification.'},null,2)};
window.sg7Speak=()=>{const text=($('voiceText')||$('langQuery'))?.value||'BIS SmartGuide';const lang=($('voiceLang')||$('lang2'))?.value||'English';if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(text);u.lang={English:'en-IN',Hindi:'hi-IN',Telugu:'te-IN',Kannada:'kn-IN',Tamil:'ta-IN',Malayalam:'ml-IN'}[lang]||'en-IN';speechSynthesis.speak(u)}$('sg7Result').textContent=JSON.stringify({language:lang,status:'BROWSER_VOICE_PIPELINE',text},null,2)};
window.sg7Test=async()=>{try{$('sg7Result').textContent=JSON.stringify(await api('/v5/test-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({standard:$('trStd').value,text:$('trText').value})}),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7Analytics=()=>{const products=JSON.parse(localStorage.getItem('sg7_products')||'[]');$('sg7Result').textContent=JSON.stringify({saved_products:products.length,saved_products_list:products,local_drafts: Object.keys(localStorage).filter(k=>k.startsWith('sg7_')).length,analytics_scope:'Local workspace prototype; server assessment analytics remain in existing Analytics/Passport.'},null,2)};
window.sg7Graph=()=>{$('sg7Result').innerHTML='<div class="sg7-result">Product → Standard → Clause → Requirement → Test → Laboratory → Certificate/QCO<br><br>Each edge should be backed by retrieved BIS evidence before being treated as authoritative.</div>'};
window.sg7Hybrid=async()=>{try{$('sg7Result').textContent=JSON.stringify(await api('/v5/hybrid-search?q='+encodeURIComponent($('hybridQ').value)),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7Guard=async()=>{try{$('sg7Result').textContent=JSON.stringify(await api('/v5/evidence-guard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answer:$('guard').value})}),null,2)}catch(e){$('sg7Result').textContent=e.message}};
window.sg7Review=()=>sg7Local('review',{case_id:$('reviewCase').value,decision:$('reviewDecision').value,note:$('reviewNote').value,reviewed_at:new Date().toISOString()});
window.sg7RegisterPWA=()=>{if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js').then(()=>{$('sg7Result').textContent='Service worker registered; PWA shell ready.'}).catch(e=>$('sg7Result').textContent=e.message)}else $('sg7Result').textContent='Service workers are not supported in this browser.'};
async function loadStatus(){try{const d=await api('/v5/feature-status');const a=d.features||[];const active=a.filter(x=>String(x.status).startsWith('ACTIVE')).length;const out=$('sg7Result');if(out)out.textContent=JSON.stringify({backend_version:d.version,backend_feature_count:a.length,active_or_integrated:active},null,2)}catch(e){const out=$('sg7Result');if(out)out.textContent='Backend status unavailable: '+e.message}}
function sg7Router(){}
function init(){const old=$('v6Nav');if(old)old.remove();const oldPage=$('v6');if(oldPage)oldPage.remove();const b=nav();if(b)b.onclick=()=>{show();loadStatus()};if(!document.getElementById('sg7Style')){const l=document.createElement('link');l.id='sg7Style';l.rel='stylesheet';l.href='smartguide-v7.css';document.head.appendChild(l)}if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
