/* BIS SmartGuide Advanced Intelligence — rebuilt workflow console v8. */
(() => {
  'use strict';
  const API='https://sih26107-bis-smartguide-api.onrender.com';
  const $=id=>document.getElementById(id);
  const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const pretty=x=>{try{return JSON.stringify(x,null,2)}catch{return String(x)}};
  async function api(path,opt={}){const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||d.message||`Request failed (${r.status})`);return d}
  function nav(){const n=document.querySelector('.nav');if(!n||$('v6Nav'))return;const b=document.createElement('button');b.id='v6Nav';b.innerHTML='<span>✦</span><span>Advanced Intelligence</span>';b.onclick=()=>{if(window.page)window.page('v6',b,'Advanced Intelligence');loadStatus()};n.appendChild(b)}
  function card(icon,title,desc,fn){return `<button class="sg-v6-card sg-v6-feature" onclick="${fn}()" type="button"><span class="sg-v6-icon">${icon}</span><h3>${title}</h3><p>${desc}</p><span class="sg-v6-open">Open workflow →</span></button>`}
  function page(){if($('v6'))return;const m=document.querySelector('.content');if(!m)return;const s=document.createElement('section');s.id='v6';s.className='page';s.innerHTML=`
    <div class="section-head"><div><h2>Advanced Intelligence</h2><p>Rebuilt source-grounded workflows for product intelligence, verification, testing, laboratories, engineering and reporting.</p></div><span class="sg-v6-badge">REBUILT V8</span></div>
    <div class="sg-v6-kpis"><div class="sg-v6-kpi"><b id="v6Active">—</b><span class="sg-v6-muted">Functional workflows</span></div><div class="sg-v6-kpi"><b>V4 + V8</b><span class="sg-v6-muted">Evidence + intelligence</span></div><div class="sg-v6-kpi"><b>6</b><span class="sg-v6-muted">Official BIS sources</span></div><div class="sg-v6-kpi"><b>0</b><span class="sg-v6-muted">Automated certificates</span></div></div>
    <div class="sg-v6-grid">
      ${card('🔎','Product AI','Rank applicable standards from a product description','openProduct')}
      ${card('✓','ISI / CM-L','Screen marks and licence references','openMark')}
      ${card('📄','Test Reports','Extract measurements without inventing limits','openTest')}
      ${card('🧪','Lab Matcher','Prepare exact IS/test scope lookup','openLab')}
      ${card('📋','QCO + Amendment','Screen likely impact areas','openAmendment')}
      ${card('🧊','3D CAD / STL','Scan ASCII and binary STL geometry','openSTL')}
      ${card('🏷️','Label / Packaging','Screen key marking fields','openLabel')}
      ${card('🛒','Procurement AI','Screen product, raw material and HS format','openProcurement')}
      ${card('⚠️','Issue Report','Create a structured complaint draft','openIssue')}
    </div>
    <div class="sg-v6-section"><div class="section-head"><div><h2>Live feature status</h2><p class="sg-v6-muted">Functional means the workflow is implemented. Official BIS decisions remain source-bound.</p></div><button class="btn ghost" type="button" onclick="runV8SelfTest()">Run self-test</button></div><div id="v6Status" class="sg-v6-grid"><div class="sg-v6-card">Loading…</div></div><div id="v8SelfTest" class="sg-v6-result"></div></div>
    <div id="v6Tool" class="sg-v6-output"></div>`;m.appendChild(s)}
  function tool(title,body){const el=$('v6Tool');el.innerHTML=`<div class="sg-v6-card sg-v6-tool"><div class="section-head"><div><h2>${title}</h2></div><button class="btn" type="button" onclick="$('v6Tool').innerHTML=''">Close</button></div>${body}</div>`;el.scrollIntoView({behavior:'smooth',block:'start'})}
  function output(d){const out=$('v6Out');if(out)out.innerHTML=`<div class="sg-v6-result-head"><b>Workflow result</b><button class="btn ghost" type="button" onclick="navigator.clipboard?.writeText(this.closest('.sg-v6-result').querySelector('pre').textContent)">Copy</button></div><pre>${esc(pretty(d))}</pre>`}
  function loading(){if($('v6Out'))$('v6Out').innerHTML='<div class="sg-v6-loading">Running SmartGuide analysis…</div>'}
  function fail(e){output({error:e?.message||String(e),hint:'Check backend health and retry.'})}
  window.openProduct=()=>tool('Product → ranked standards',`<div class="sg-v6-form"><textarea id="v6Product" class="full" placeholder="Example: 1200W stainless-steel electric kettle for household use with automatic shutoff"></textarea><div><button class="btn primary" onclick="runProduct()">Rank standards</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runProduct=async()=>{loading();try{output(await api('/v5/product-intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description:$('v6Product').value})}))}catch(e){fail(e)}};
  window.openMark=()=>tool('ISI + CM/L verification',`<div class="sg-v6-form"><textarea id="v6MarkText" class="full" placeholder="Paste label/licence text"></textarea><input id="v6Licence" placeholder="Licence / CM-L number (optional)"><div><button class="btn primary" onclick="runMark()">Screen mark</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runMark=async()=>{loading();try{output(await api('/v5/verify-mark',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('v6MarkText').value,licence:$('v6Licence').value})}))}catch(e){fail(e)}};
  window.openTest=()=>tool('Test-report intelligence',`<div class="sg-v6-form"><input id="v6Std" placeholder="Applicable IS number (optional)"><textarea id="v6Report" class="full" placeholder="Voltage: 230 V\nPower: 1200 W\nLeakage current: 0.4 mA"></textarea><div><button class="btn primary" onclick="runTest()">Parse report</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runTest=async()=>{loading();try{output(await api('/v5/test-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({standard:$('v6Std').value,text:$('v6Report').value})}))}catch(e){fail(e)}};
  window.openLab=()=>tool('Intelligent laboratory workflow',`<div class="sg-v6-form"><input id="v6LabProduct" placeholder="Product"><input id="v6LabStd" placeholder="IS number"><input id="v6LabTest" class="full" placeholder="Required test / parameter"><div><button class="btn primary" onclick="runLab()">Prepare lab lookup</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runLab=async()=>{loading();try{const q=new URLSearchParams({product:$('v6LabProduct').value,standard:$('v6LabStd').value,test:$('v6LabTest').value});const d=await api('/v5/lab-match?'+q);output(d);$('v6Out').insertAdjacentHTML('afterbegin','<div class="sg-v6-map"><b>Official BIS LIMS lookup</b><p>Use the returned IS number and test scope in the official BIS LIMS directory.</p><a class="btn ghost" target="_blank" rel="noopener" href="https://lims.bis.gov.in/home/search_is_number/">Open BIS LIMS →</a></div>')}catch(e){fail(e)}};
  window.openAmendment=()=>tool('QCO / amendment impact',`<div class="sg-v6-form"><input id="v6AmStd" placeholder="Standard / IS"><input id="v6AmProduct" placeholder="Product"><textarea id="v6AmText" class="full" placeholder="Paste amendment or QCO text/summary"></textarea><div><button class="btn primary" onclick="runAmendment()">Analyze impact</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runAmendment=async()=>{loading();try{output(await api('/v5/amendment-impact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({standard:$('v6AmStd').value,product:$('v6AmProduct').value,amendment:$('v6AmText').value})}))}catch(e){fail(e)}};
  window.openSTL=()=>tool('3D CAD / STL engineering scanner',`<div class="sg-v6-form"><input id="v6STL" type="file" accept=".stl" class="full"><input id="v6X" type="number" step="any" placeholder="Max X dimension (optional)"><input id="v6Y" type="number" step="any" placeholder="Max Y dimension (optional)"><input id="v6Z" type="number" step="any" placeholder="Max Z dimension (optional)"><div><button class="btn primary" onclick="runSTL()">Scan STL</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runSTL=async()=>{loading();try{const f=$('v6STL').files[0];if(!f)return output({error:'Select an STL file'});const fd=new FormData();fd.append('file',f);[['x','v6X'],['y','v6Y'],['z','v6Z']].forEach(([a,id])=>{if($(id).value)fd.append('max_'+a,$(id).value)});output(await api('/v5/stl-scan',{method:'POST',body:fd}))}catch(e){fail(e)}};
  window.openLabel=()=>tool('Label / packaging screening',`<div class="sg-v6-form"><textarea id="v6Label" class="full" placeholder="Paste label/package text"></textarea><div><button class="btn primary" onclick="runLabel()">Check label</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runLabel=async()=>{loading();try{output(await api('/v5/label-check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('v6Label').value})}))}catch(e){fail(e)}};
  window.openProcurement=()=>tool('Procurement intelligence',`<div class="sg-v6-form"><input id="v6Proc" placeholder="Product"><input id="v6HS" placeholder="HS code (4–8 digits, optional)"><input id="v6Raw" class="full" placeholder="Raw material / component"><div><button class="btn primary" onclick="runProcurement()">Screen procurement</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runProcurement=async()=>{loading();try{output(await api('/v5/procurement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:$('v6Proc').value,hs_code:$('v6HS').value,raw_material:$('v6Raw').value})}))}catch(e){fail(e)}};
  window.openIssue=()=>tool('Issue / counterfeit report draft',`<div class="sg-v6-form"><input id="v6IssueProduct" placeholder="Product (optional)"><textarea id="v6Issue" class="full" placeholder="Describe the suspected issue, marking problem or safety concern"></textarea><div><button class="btn primary" onclick="runIssue()">Create case draft</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runIssue=async()=>{loading();try{output(await api('/v5/issue-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:$('v6IssueProduct').value,issue:$('v6Issue').value})}))}catch(e){fail(e)}};
  window.runV8SelfTest=async()=>{const el=$('v8SelfTest');if(el)el.innerHTML='<div class="sg-v6-loading">Running backend self-test…</div>';try{const d=await api('/v5/self-test');if(el)el.innerHTML='<pre>'+esc(pretty(d))+'</pre>'}catch(e){if(el)el.innerHTML='<pre>'+esc(JSON.stringify({ok:false,error:e.message},null,2))+'</pre>'}};
  async function loadStatus(){try{const d=await api('/v5/feature-status');const a=d.features||[];$('v6Active').textContent=a.filter(x=>String(x.status).startsWith('FUNCTIONAL')).length;$('v6Status').innerHTML=a.map(x=>`<div class="sg-v6-card sg-v6-status-card"><span class="sg-v6-badge">${esc(x.status)}</span><h3>${esc(x.feature)}</h3></div>`).join('')}catch(e){$('v6Status').innerHTML='<div class="sg-v6-card sg-v6-warn"><b>Backend unavailable</b><p>'+esc(e.message)+'</p></div>'}}
  function init(){nav();page();setTimeout(()=>{nav();page()},500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
