/* BIS SmartGuide V6 — functional advanced feature console. */
(() => {
  const API='https://sih26107-bis-smartguide-api.onrender.com';
  const $=id=>document.getElementById(id);
  const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const json=x=>{try{return JSON.stringify(x,null,2)}catch{return String(x)}};
  async function api(path,opt={}){const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||d.message||`Request failed (${r.status})`);return d}
  function nav(){const n=document.querySelector('.nav');if(!n||$('v6Nav'))return;const b=document.createElement('button');b.id='v6Nav';b.innerHTML='<span>✦</span><span>Advanced Intelligence</span>';b.onclick=()=>{if(typeof window.page==='function')window.page('v6',b,'Advanced Intelligence');loadStatus()};n.appendChild(b)}
  function page(){if($('v6'))return;const m=document.querySelector('.content');if(!m)return;const s=document.createElement('section');s.id='v6';s.className='page';s.innerHTML=`
    <div class="section-head"><div><h2>Advanced Intelligence</h2><p>Engineering, verification, laboratory, amendment and enterprise workflows — grounded in official BIS source boundaries.</p></div><span class="sg-v6-badge">V6 INTELLIGENCE LAYER</span></div>
    <div class="sg-v6-kpis"><div class="sg-v6-kpi"><b id="v6Active">—</b><span class="sg-v6-muted">Feature workflows active</span></div><div class="sg-v6-kpi"><b>V4 + V6</b><span class="sg-v6-muted">Evidence + intelligence</span></div><div class="sg-v6-kpi"><b>6</b><span class="sg-v6-muted">Official BIS source links</span></div><div class="sg-v6-kpi"><b>0</b><span class="sg-v6-muted">Automated BIS certificates</span></div></div>
    <div class="sg-v6-grid">
      ${card('🔎','Product AI','Product → ranked BIS standards','openProduct')}
      ${card('✓','ISI / CM-L','Mark and licence screening','openMark')}
      ${card('📄','Test Reports','Extract reported measurements','openTest')}
      ${card('🧪','Lab Matcher','Match standard/test to BIS lab scope','openLab')}
      ${card('📋','QCO + Amendment','Screen affected requirements','openAmendment')}
      ${card('🧊','3D CAD / STL','Measure supplied STL geometry','openSTL')}
      ${card('🏷️','Label / Packaging','Check key product marking fields','openLabel')}
      ${card('🛒','Procurement AI','Product, raw material and HS screening','openProcurement')}
      ${card('⚠️','Issue Report','Create a structured consumer case','openIssue')}
    </div>
    <div class="sg-v6-section"><h2>Feature status</h2><p class="sg-v6-muted">Active means the workflow is implemented. Official registry decisions remain source-bound.</p><div id="v6Status" class="sg-v6-grid"><div class="sg-v6-card">Loading…</div></div></div>
    <div id="v6Tool" class="sg-v6-output"></div>`;m.appendChild(s)}
  function card(icon,title,desc,fn){return `<button class="sg-v6-card sg-v6-feature" onclick="${fn}()" type="button"><span class="sg-v6-icon">${icon}</span><h3>${title}</h3><p>${desc}</p><span class="sg-v6-open">Open workflow →</span></button>`}
  function tool(title,body){const el=$('v6Tool');el.innerHTML=`<div class="sg-v6-card sg-v6-tool"><div class="section-head"><div><h2>${title}</h2></div><button class="btn" type="button" onclick="document.getElementById('v6Tool').innerHTML=''">Close</button></div>${body}</div>`;el.scrollIntoView({behavior:'smooth',block:'start'})}
  function output(d){const out=$('v6Out');if(!out)return;out.innerHTML=`<div class="sg-v6-result-head"><b>Workflow result</b><button class="btn ghost" type="button" onclick="navigator.clipboard?.writeText(this.closest('.sg-v6-result').querySelector('pre').textContent)">Copy</button></div><pre>${esc(json(d))}</pre>`}
  function loading(){const out=$('v6Out');if(out)out.innerHTML='<div class="sg-v6-loading">Running SmartGuide analysis…</div>'}
  function err(e){output({error:e?.message||String(e),hint:'Check the Render API health and try again.'})}
  window.openProduct=()=>tool('Product → standard intelligence',`<div class="sg-v6-form"><div class="full"><textarea id="v6Product" placeholder="Describe the product, model, use, power/rating and important attributes…"></textarea></div><div class="full sg-v6-actions"><button class="btn primary" onclick="runProduct()">Rank standards</button><button class="btn ghost" onclick="document.getElementById('v6Product').value='1200W stainless-steel electric kettle for household use with automatic shutoff'">Use example</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runProduct=async()=>{loading();try{output(await api('/v5/product-intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description:$('v6Product').value})}))}catch(e){err(e)}};
  window.openMark=()=>tool('ISI + CM/L verification',`<div class="sg-v6-form"><input id="v6MarkText" class="full" placeholder="Paste label / licence text"><input id="v6Licence" placeholder="Licence / CM/L number"><div><button class="btn primary" onclick="runMark()">Check markers</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runMark=async()=>{loading();try{output(await api('/v5/verify-mark',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('v6MarkText').value,licence:$('v6Licence').value})}))}catch(e){err(e)}};
  window.openTest=()=>tool('Test-report intelligence',`<div class="sg-v6-form"><input id="v6Std" placeholder="Applicable IS number (optional)"><textarea id="v6Report" class="full" placeholder="Paste test report text, e.g. Voltage: 230 V\nPower: 1200 W"></textarea><div><button class="btn primary" onclick="runTest()">Parse report</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runTest=async()=>{loading();try{output(await api('/v5/test-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({standard:$('v6Std').value,text:$('v6Report').value})}))}catch(e){err(e)}};
  window.openLab=()=>tool('Intelligent laboratory matching',`<div class="sg-v6-form"><input id="v6LabProduct" placeholder="Product"><input id="v6LabStd" placeholder="IS number"><input id="v6LabTest" class="full" placeholder="Required test / parameter"><div class="sg-v6-actions"><button class="btn primary" onclick="runLab()">Match labs</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runLab=async()=>{loading();try{const q=new URLSearchParams({product:$('v6LabProduct').value,standard:$('v6LabStd').value,test:$('v6LabTest').value});const d=await api('/v5/lab-match?'+q);output(d);const qtext=encodeURIComponent([$('v6LabProduct').value,$('v6LabStd').value,$('v6LabTest').value,'BIS laboratory'].filter(Boolean).join(' '));$('v6Out').insertAdjacentHTML('afterbegin',`<div class="sg-v6-map"><b>📍 Find nearby eligible facilities</b><p>Use the official BIS lab/LIMS scope first, then open a map search for the selected facility.</p><a class="btn ghost" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${qtext}">Open Google Maps →</a></div>`)}catch(e){err(e)}};
  window.openAmendment=()=>tool('QCO / amendment impact',`<div class="sg-v6-form"><input id="v6AmStd" placeholder="Standard / IS"><input id="v6AmProduct" placeholder="Product"><textarea id="v6AmText" class="full" placeholder="Paste amendment/QCO notice text or summary…"></textarea><div><button class="btn primary" onclick="runAmendment()">Analyze impact</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runAmendment=async()=>{loading();try{output(await api('/v5/amendment-impact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({standard:$('v6AmStd').value,product:$('v6AmProduct').value,amendment:$('v6AmText').value})}))}catch(e){err(e)}};
  window.openSTL=()=>tool('3D CAD / STL engineering scanner',`<div class="sg-v6-form"><input id="v6STL" type="file" accept=".stl" class="full"><input id="v6X" type="number" step="any" placeholder="Max X dimension (optional)"><input id="v6Y" type="number" step="any" placeholder="Max Y dimension (optional)"><input id="v6Z" type="number" step="any" placeholder="Max Z dimension (optional)"><div><button class="btn primary" onclick="runSTL()">Scan STL</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runSTL=async()=>{loading();try{const f=$('v6STL').files[0];if(!f)return output({error:'Select an STL file'});const fd=new FormData();fd.append('file',f);[['x','v6X'],['y','v6Y'],['z','v6Z']].forEach(([a,id])=>{if($(id).value)fd.append('max_'+a,$(id).value)});output(await api('/v5/stl-scan',{method:'POST',body:fd}))}catch(e){err(e)}};
  window.openLabel=()=>tool('Label / packaging compliance screen',`<div class="sg-v6-form"><textarea id="v6Label" class="full" placeholder="Paste label/package text…"></textarea><div class="sg-v6-actions"><button class="btn primary" onclick="runLabel()">Check label</button><button class="btn ghost" onclick="document.getElementById('v6Label').value='Electric Kettle\nManufactured by ABC Appliances\nModel EK-1200\nIS 302\n1200 W, 230 V\nISI CM/L-1234567'">Use example</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runLabel=async()=>{loading();try{output(await api('/v5/label-check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('v6Label').value})}))}catch(e){err(e)}};
  window.openProcurement=()=>tool('Procurement intelligence',`<div class="sg-v6-form"><input id="v6Proc" placeholder="Product"><input id="v6HS" placeholder="HS code (optional)"><input id="v6Raw" class="full" placeholder="Raw material / component"><div><button class="btn primary" onclick="runProcurement()">Screen procurement</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runProcurement=async()=>{loading();try{output(await api('/v5/procurement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:$('v6Proc').value,hs_code:$('v6HS').value,raw_material:$('v6Raw').value})}))}catch(e){err(e)}};
  window.openIssue=()=>tool('Consumer / counterfeit issue draft',`<div class="sg-v6-form"><input id="v6IssueProduct" placeholder="Product"><textarea id="v6Issue" class="full" placeholder="Describe the suspected issue…"></textarea><div><button class="btn primary" onclick="runIssue()">Create case draft</button></div></div><div id="v6Out" class="sg-v6-result"></div>`);
  window.runIssue=async()=>{loading();try{output(await api('/v5/issue-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:$('v6IssueProduct').value,issue:$('v6Issue').value})}))}catch(e){err(e)}};
  async function loadStatus(){try{const d=await api('/v5/feature-status');const a=d.features||[];$('v6Active').textContent=a.filter(x=>String(x.status).startsWith('ACTIVE')).length;$('v6Status').innerHTML=a.map((x,i)=>`<div class="sg-v6-card sg-v6-status-card"><span class="sg-v6-badge">${esc(x.status)}</span><h3>${esc(x.feature)}</h3><small>${i<13?'Workflow available':'Source-bound / integration status'}</small></div>`).join('')}catch(e){$('v6Status').innerHTML='<div class="sg-v6-card sg-v6-warn"><b>V6 backend unavailable</b><p>'+esc(e.message)+'</p></div>'}}
  function init(){nav();page();setTimeout(()=>{nav();page()},500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();